### ISSUE TITLE
Authentication requirements causes failure

### ISSUE THREAD

**Issue by lavahot** [benmatselby/sublime-jenkins-dashboard#1]
My team currently uses Assembla to authenticate logging into our Jenkins. In the future, we will also probably be moving to JIRA authentication. This apparently causes this plugin to fail when trying to access Jenkins. Is there a fix for this?

**Comment by benmatselby** [comment]
This would be an enhancement that needs to be built. I don't see it being that hard, as I believe the Jenkins API supports this.

**Comment by benmatselby** [comment]
@lavahot Hi there. This has been been implemented by @kfiku. Please update to the 1.3.0 release.
